apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mesh-server-api.fullname" . }}-environment
  labels:
    {{- include "mesh-server-api.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}