apiVersion: v1
kind: Service
metadata:
  name: {{ include "mesh-server-api.fullname" . }}
  labels: {{- include "mesh-server-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.env.PORT }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "mesh-server-api.selectorLabels" . | nindent 4 }}
